In [4]:
# Dependencies and Setup
import pandas as pd

# File to Load 
vaccination_data= "Raw Data/Measle Vaccination.csv"
cases_data = "Raw Data/Measle Cases.csv"

# Read Vaccination and Case Data File and store into Pandas Data Frames
vaccination = pd.read_csv(vaccination_data)
cases = pd.read_csv(cases_data)

In [10]:
# Clean data sets and create dataframes
vaccination_df = pd.DataFrame(vaccination)

# Remove uneccessary columns
vaccination_df.drop(['INDICATOR','SUBJECT', 'MEASURE', 'FREQUENCY', 'Flag Codes'], axis=1, inplace=True)

# Rename column titles
vaccination_df.rename(columns={'LOCATION':'Country', 'TIME':'Year', 'Value':'Measle Vaccinated Rate'}, inplace=True)

# Remove the year 2018 to keep years consistent for all countries
vaccination_df = vaccination_df[vaccination_df.Year != 2018]
vaccination_df = vaccination_df[vaccination_df.Year != 2017]

# Display all rows in the dataframe
# pd.set_option('display.max_rows', 308)

# Display dataframe
# vaccination_df

In [11]:
cases_df = pd.DataFrame(cases)

# Replace NaN with a value of zero
cases_df.fillna(0)

# Remove uneccessary columns
cases_df.drop(['Region', 'ISO3'], axis=1, inplace=True)

# Create a 'Total Measle Cases' column that sums up the number of cases throughout the year
cases_df['Total Measle Cases']= cases_df.values[:,3:14].sum(axis=1)

# Delete years 2018 and 2019 to make all datasets years consistent
cases_df = cases_df[cases_df.Year != 2017]
cases_df = cases_df[cases_df.Year != 2018]
cases_df = cases_df[cases_df.Year != 2019]

# Drop uneccessary columns
cases_df.drop(['January','February','March','April','May','June','July','August','September','October','November','December'],axis=1, inplace=True)

# Display all rows in the dataframe
# pd.set_option('display.max_rows', 1358)

# Display dataframe
cases_df

           Country  Year Total Measle Cases
0           Angola  2011                175
1           Angola  2012               4097
2           Angola  2013               5839
3           Angola  2014              10841
4           Angola  2015                 99
5           Angola  2016                 48
9          Burundi  2011                 57
10         Burundi  2012                 44
11         Burundi  2013                  0
12         Burundi  2014                  8
13         Burundi  2015                  7
14         Burundi  2016                 16
18           Benin  2011                402
19           Benin  2012                261
20           Benin  2013                676
21           Benin  2014                630
22           Benin  2015                 47
23           Benin  2016                 91
27    Burkina Faso  2011                273
28    Burkina Faso  2012                775
29    Burkina Faso  2013                361
30    Burkina Faso  2014                391
31    Burkina Faso  2015                 84
32    Burkina Faso  2016                223
36        Botswana  2011                138
37        Botswana  2012                 10
38        Botswana  2013                  1
39        Botswana  2014                 87
40        Botswana  2015                  2
41        Botswana  2016                  2
...            ...   ...                ...
1701         Tonga  2011                  0
1702         Tonga  2012                  0
1703         Tonga  2013                  0
1704         Tonga  2014                  0
1705         Tonga  2015                  0
1706         Tonga  2016                  0
1710        Tuvalu  2011                  0
1711        Tuvalu  2012                  0
1712        Tuvalu  2013                  0
1713        Tuvalu  2014                  0
1714        Tuvalu  2015                  0
1715        Tuvalu  2016                  0
1719      Viet Nam  2011                641
1720      Viet Nam  2012                581
1721      Viet Nam  2013               1276
1722      Viet Nam  2014              16004
1723      Viet Nam  2015                773
1724      Viet Nam  2016                476
1728       Vanuatu  2011                  0
1729       Vanuatu  2012                  0
1730       Vanuatu  2013                  0
1731       Vanuatu  2014                  5
1732       Vanuatu  2015                 16
1733       Vanuatu  2016                  0
1737         Samoa  2011                  0
1738         Samoa  2012                  0
1739         Samoa  2013                  0
1740         Samoa  2014                  0
1741         Samoa  2015                  0
1742         Samoa  2016                  0

[1164 rows x 3 columns]

In [12]:
# Merge vaccination_df and cases_df into one dataframe
data_complete = pd.merge(vaccination_df, cases_df, how="inner", on=["Country","Year"])

data_complete = data_complete.set_index(["Country","Year"])
data_complete

# # Display all rows in the dataframe
# pd.set_option('display.max_rows', 300)

# # Append countries column
# data_complete = data_complete.set_index('Country', append=True).swaplevel(0,1)

# # Display dataframe
# data_complete.drop(index)

                     Measle Vaccinated Rate Total Measle Cases
Country        Year
Australia      2011                      94                171
               2012                      94                196
               2013                      94                151
               2014                      94                262
               2015                      95                 64
               2016                      95                 93
Austria        2011                      84                206
               2012                      88                 29
               2013                      92                 75
               2014                      96                 87
               2015                      96                267
               2016                      95                 28
Belgium        2011                      95               1145
               2012                      96                 94
               2013                      96                 43
               2014                      96                 71
               2015                      96                 54
               2016                      96                 75
Canada         2011                      88                NaN
               2012                      98                  9
               2013                      90                 82
               2014                      90                418
               2015                      90                180
               2016                      90                  9
Czech Republic 2011                      98                 18
               2012                      98                 17
               2013                      99                 15
               2014                      99                222
               2015                      99                  5
               2016                      98                  7
...                                     ...                ...
Slovenia       2011                      96                 22
               2012                      95                  1
               2013                      94                  1
               2014                      94                 52
               2015                      94                 12
               2016                      92                  1
South Africa   2011                      89                115
               2012                      89                 35
               2013                      87                 49
               2014                      92                141
               2015                      97                595
               2016                      96                 22
Costa Rica     2011                      83                NaN
               2012                      90                NaN
               2013                      91                NaN
               2014                      95                  1
               2015                      93                  0
               2016                      93                  0
Latvia         2011                      92                  0
               2012                      90                  2
               2013                      96                  0
               2014                      95                 36
               2015                      96                  0
               2016                      93                  0
Lithuania      2011                      94                  7
               2012                      93                  2
               2013                      93                 35
               2014                      93                 11
               2015                      94                 51
               2016                      94                 22

[234 rows x 2 columns]